# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
target 'YSIMQClient_Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YSIMQClient_Demo
  pod 'Protobuf', '~> 3.11.4'
  pod "YSIMQClient", path: '../'
end
